In [1]:
# SQL Pyton connect

In [2]:
from sqlalchemy import create_engine, text
import pymysql
import pandas as pd
import os
import urllib.parse

In [3]:
password = urllib.parse.quote_plus("Mysql@123")

In [4]:
engine1 = create_engine(f"mysql+pymysql://root:{password}@localhost:3306/piit")
engine1

Engine(mysql+pymysql://root:***@localhost:3306/piit)

In [5]:
# function to run the query with parameters or query
def q(sql, **params):
 with engine1.connect() as conn:
  return pd.read_sql(text(sql), conn, params=params)

In [6]:
q('show tables')

  Tables_in_piit
0           dept
1            emp
2       students

In [7]:
q('select * from dept')

   deptno       dname       loc
0    10.0  ACCOUNTING  NEW YORK
1    20.0    RESEARCH    DALLAS
2    30.0       SALES   CHICAGO
3    40.0  OPERATIONS    BOSTON
4    10.0  ACCOUNTING  NEW YORK
5    20.0    RESEARCH    DALLAS
6    30.0       SALES   CHICAGO
7    40.0  OPERATIONS    BOSTON

In [8]:
q('select * from emp')

    empno   ename        job     mgr    hiredate     sal    comm  deptno
0    1235  SEVKET    ANALYST  7839.0  1990-12-17  6000.0   100.0      20
1    7369   SMITH      CLERK  7902.0  1980-12-17   800.0     NaN      20
2    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
3    7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
4    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0     NaN      20
5    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30
6    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     NaN      30
7    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     NaN      10
8    7788   SCOTT    ANALYST  7566.0  1982-12-09  3000.0     NaN      20
9    7839    KING  PRESIDENT     NaN  1981-11-17  5000.0     NaN      10
10   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0      30
11   7876   ADAMS      CLERK  7788.0  1983-01-12  1100.0     NaN      20
12   7900   JAMES      CLERK  7698.0  1981-12-03   950.0     NaN      30
13   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0     NaN      20
14   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     NaN      10

In [10]:
emp = q('select * from emp')
emp.head()

   empno   ename       job     mgr    hiredate     sal   comm  deptno
0   1235  SEVKET   ANALYST  7839.0  1990-12-17  6000.0  100.0      20
1   7369   SMITH     CLERK  7902.0  1980-12-17   800.0    NaN      20
2   7499   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0  300.0      30
3   7521    WARD  SALESMAN  7698.0  1981-02-22  1250.0  500.0      30
4   7566   JONES   MANAGER  7839.0  1981-04-02  2975.0    NaN      20

In [13]:
dept = q('select * from dept')
dept.head()

   deptno       dname       loc
0    10.0  ACCOUNTING  NEW YORK
1    20.0    RESEARCH    DALLAS
2    30.0       SALES   CHICAGO
3    40.0  OPERATIONS    BOSTON
4    10.0  ACCOUNTING  NEW YORK

In [16]:
empdept= q("SELECT * FROM emp JOIN dept ON emp.deptno = dept.deptno")
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,deptno,dname,loc
0,1235,SEVKET,ANALYST,7839.0,1990-12-17,6000.0,100.0,20,20.0,RESEARCH,DALLAS
1,1235,SEVKET,ANALYST,7839.0,1990-12-17,6000.0,100.0,20,20.0,RESEARCH,DALLAS
2,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,20.0,RESEARCH,DALLAS
3,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,20.0,RESEARCH,DALLAS
4,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,30.0,SALES,CHICAGO

In [20]:
empdept.groupby('dname').size()

dname
ACCOUNTING     6
RESEARCH      12
SALES         12
dtype: int64

In [21]:
empdept = empdept.drop_duplicates()
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,deptno,dname,loc
0,1235,SEVKET,ANALYST,7839.0,1990-12-17,6000.0,100.0,20,20.0,RESEARCH,DALLAS
2,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,20.0,RESEARCH,DALLAS
4,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,30.0,SALES,CHICAGO
6,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,30.0,SALES,CHICAGO
8,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,NaN,20,20.0,RESEARCH,DALLAS

In [22]:
# Finding the average and total salary for each department
budget_analysis = empdept.groupby('dname')['sal'].agg(['mean', 'sum', 'count'])
budget_analysis

                   mean      sum  count
dname
ACCOUNTING  2916.666667   8750.0      3
RESEARCH    2812.500000  16875.0      6
SALES       1566.666667   9400.0      6

In [24]:
# Counting how many people hold each job title in each location
job_structure = empdept.groupby(['loc', 'job']).size().unstack(fill_value=0)
job_structure

job       ANALYST  CLERK  MANAGER  PRESIDENT  SALESMAN
loc
CHICAGO         0      1        1          0         4
DALLAS          3      2        1          0         0
NEW YORK        0      1        1          1         0

In [25]:
# Finding employees who earn more than 2000 and work in RESEARCH
high_earners = empdept[(empdept['sal'] > 2000) & (empdept['dname'] == 'RESEARCH')]
high_earners[['ename', 'job', 'sal']]

     ename      job     sal
0   SEVKET  ANALYST  6000.0
8    JONES  MANAGER  2975.0
16   SCOTT  ANALYST  3000.0
26    FORD  ANALYST  3000.0

In [26]:
dept_finances = empdept.groupby('dname')['sal'].agg(['sum', 'mean', 'max']).round(2)
dept_finances.columns = ['Total_Payroll', 'Average_Sal', 'Highest_Sal']
dept_finances

            Total_Payroll  Average_Sal  Highest_Sal
dname
ACCOUNTING         8750.0      2916.67       5000.0
RESEARCH          16875.0      2812.50       6000.0
SALES              9400.0      1566.67       2850.0

In [27]:
# Create a matrix of job titles across locations
job_matrix = pd.crosstab(empdept['loc'], empdept['job'])
job_matrix

job       ANALYST  CLERK  MANAGER  PRESIDENT  SALESMAN
loc
CHICAGO         0      1        1          0         4
DALLAS          3      2        1          0         0
NEW YORK        0      1        1          1         0

In [28]:
# Calculate company-wide average
avg_sal = empdept['sal'].mean()

In [29]:
# Filter for those above the average
above_avg = empdept[empdept['sal'] > avg_sal]
above_avg[['ename', 'job', 'sal', 'dname']]

     ename        job     sal       dname
0   SEVKET    ANALYST  6000.0    RESEARCH
8    JONES    MANAGER  2975.0    RESEARCH
12   BLAKE    MANAGER  2850.0       SALES
14   CLARK    MANAGER  2450.0  ACCOUNTING
16   SCOTT    ANALYST  3000.0    RESEARCH
18    KING  PRESIDENT  5000.0  ACCOUNTING
26    FORD    ANALYST  3000.0    RESEARCH

In [30]:
empdept.sort_values('sal', ascending=False).head(3)

,empno,ename,job,mgr,hiredate,sal,comm,deptno,deptno,dname,loc
0,1235,SEVKET,ANALYST,7839.0,1990-12-17,6000.0,100.0,20,20.0,RESEARCH,DALLAS
18,7839,KING,PRESIDENT,NaN,1981-11-17,5000.0,NaN,10,10.0,ACCOUNTING,NEW YORK
16,7788,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20,20.0,RESEARCH,DALLAS

In [32]:
# Do this right after your cleaning step
empdept = empdept.drop_duplicates().copy()

In [33]:
# Updated code to avoid the warning
empdept.loc[:, 'total_comp'] = empdept['sal'] + empdept['comm'].fillna(0)
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,deptno,dname,loc,total_comp
0,1235,SEVKET,ANALYST,7839.0,1990-12-17,6000.0,100.0,20,20.0,RESEARCH,DALLAS,6100.0
2,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,20.0,RESEARCH,DALLAS,800.0
4,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,30.0,SALES,CHICAGO,1900.0
6,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,30.0,SALES,CHICAGO,1750.0
8,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,NaN,20,20.0,RESEARCH,DALLAS,2975.0

In [34]:
# Simple way to see the count of each category
job_counts = empdept['job'].value_counts()
job_counts

job
CLERK        4
SALESMAN     4
ANALYST      3
MANAGER      3
PRESIDENT    1
Name: count, dtype: int64

In [37]:
# Using the .between() function is very clean
mid_range_earners = empdept[empdept['sal'].between(1000, 3000)]
mid_range_earners[['ename', 'sal']]

     ename     sal
4    ALLEN  1600.0
6     WARD  1250.0
8    JONES  2975.0
10  MARTIN  1250.0
12   BLAKE  2850.0
14   CLARK  2450.0
16   SCOTT  3000.0
20  TURNER  1500.0
22   ADAMS  1100.0
26    FORD  3000.0
28  MILLER  1300.0